logging:
  level:
    root: info
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mabatisDB?characterEncoding=utf-8&useSSL=false
    username: root
    password: lovo
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB
  redis:
    database: 0
    host: 47.108.185.142
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 2000



  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    cache: false
    mode: HTML
    suffix: .html
    encoding: utf-8
