logging:
  level:
    root: info
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mabatisDB?characterEncoding=utf-8&useSSL=false
    username: root
    password: lovo
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    cache: false
    mode: HTML
    suffix: .html
    encoding: utf-8